modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/sprucians/FirmasDelight/issues/"
[[mods]]
modId="firmasdelight"
version="${file.jarVersion}"
displayName="Firma's Delight"
logoFile="firmasdelight.png"
credits="Special thanks to Tictim"
authors="zoniic645"
description='''
Make comatibility to TFC and farmer's Delight
'''